name: basttrafik
description: "Interaktiv busskarta Ã¶ver GÃ¶teborg."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '^3.10.0'

dependencies:
  flutter:
    sdk: flutter
  xml: ^6.5.0
  basttrafik:
    git:
      url: https://github.com/Mabbai/basttrafik
      ref: main

flutter:
  uses-material-design: true
  assets:
    - assets/images/map.svg
    - assets/images/map.png
    - assets/images/map.jpg