name: basttrafik
description: "Interaktiv busskarta över Göteborg."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '^3.10.0'

dependencies:
  flutter:
    sdk: flutter
  xml: ^6.5.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/map.svg
    - assets/images/map.png
    - assets/images/map.jpg
    - assets/data/stations.json
    - assets/data/map_config.json
